ErrorLogApp/main/default/objects/CDER_ErrorLog__c/CDER_ErrorLog__c.object-meta.xml
<CustomObject>
    <label>CDER_ErrorLog</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>CDER_ErrorLog Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CDER_ErrorLogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ErrorLogApp/main/default/objects/CDER_ErrorLog__c/fields/ErrorCause__c.field-meta.xml
<CustomField>
    <fullName>ErrorCause__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>ErrorCause</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ErrorLogApp/main/default/objects/CDER_ErrorLog__c/fields/ExceptionMessage__c.field-meta.xml
<CustomField>
    <fullName>ExceptionMessage__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>ExceptionMessage</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

ErrorLogApp/main/default/objects/CDER_ErrorLog__c/fields/ExceptionStackTrace__c.field-meta.xml
<CustomField>
    <fullName>ExceptionStackTrace__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>ExceptionStackTrace</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

ErrorLogApp/main/default/objects/CDER_ErrorLog__c/fields/ExceptionType__c.field-meta.xml
<CustomField>
    <fullName>ExceptionType__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>ExceptionType</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ErrorLogApp/main/default/objects/CDER_ErrorLog__c/fields/LineNumber__c.field-meta.xml
<CustomField>
    <fullName>LineNumber__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>LineNumber</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

ErrorLogApp/main/default/objects/CDER_ErrorLog__c/fields/Origin__c.field-meta.xml
<CustomField>
    <fullName>Origin__c</fullName>
    <label>Origin</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Salesforce</fullName>
            </value>
            <value>
                <fullName>Mulesoft</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ErrorLogApp/main/default/objects/CDER_ErrorLog__c/fields/OriginApplication__c.field-meta.xml
<CustomField>
    <fullName>OriginApplication__c</fullName>
    <label>OriginApplication</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>OMUFA</fullName>
            </value>
            <value>
                <fullName>Cares</fullName>
            </value>
            <value>
                <fullName>ResearchIND</fullName>
            </value>
            <value>
                <fullName>PLAIR</fullName>
            </value>
            <value>
                <fullName>OrphanDrug</fullName>
            </value>
            <value>
                <fullName>MeetingRequest</fullName>
            </value>
            <value>
                <fullName>RDRC</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ErrorLogApp/main/default/objects/CDER_ErrorLog__c/fields/OriginComponent__c.field-meta.xml
<CustomField>
    <fullName>OriginComponent__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>OriginComponent</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ErrorLogApp/main/default/objects/CDER_ErrorLog__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>This field is intended for O&amp;M team to review the exception by filtering based on Status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>InProcess</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ErrorLogApp/main/default/objects/CDER_Log_Exception_Event__e/CDER_Log_Exception_Event__e.object-meta.xml
<CustomObject>
    <description>This platform event contains all information need for further Error Handling</description>
    <label>CDER Log Exception Event</label>
    <pluralLabel>CDER Log Exception Events</pluralLabel>
</CustomObject>

ErrorLogApp/main/default/objects/CDER_Log_Exception_Event__e/fields/ErrorCause__c.field-meta.xml
<CustomField>
    <fullName>ErrorCause__c</fullName>
    <label>ErrorCause</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ErrorLogApp/main/default/objects/CDER_Log_Exception_Event__e/fields/ExceptionMessage__c.field-meta.xml
<CustomField>
    <fullName>ExceptionMessage__c</fullName>
    <label>ExceptionMessage</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

ErrorLogApp/main/default/objects/CDER_Log_Exception_Event__e/fields/ExceptionStackTrace__c.field-meta.xml
<CustomField>
    <fullName>ExceptionStackTrace__c</fullName>
    <label>ExceptionStackTrace</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

ErrorLogApp/main/default/objects/CDER_Log_Exception_Event__e/fields/ExceptionType__c.field-meta.xml
<CustomField>
    <fullName>ExceptionType__c</fullName>
    <label>ExceptionType</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ErrorLogApp/main/default/objects/CDER_Log_Exception_Event__e/fields/LineNumber__c.field-meta.xml
<CustomField>
    <fullName>LineNumber__c</fullName>
    <label>LineNumber</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

ErrorLogApp/main/default/objects/CDER_Log_Exception_Event__e/fields/Origin__c.field-meta.xml
<CustomField>
    <fullName>Origin__c</fullName>
    <description>Should contain the Origin Layer, e.g Salesforce or Mulesoft</description>
    <label>Origin</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

ErrorLogApp/main/default/objects/CDER_Log_Exception_Event__e/fields/OriginApplication__c.field-meta.xml
<CustomField>
    <fullName>OriginApplication__c</fullName>
    <label>OriginApplication</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ErrorLogApp/main/default/objects/CDER_Log_Exception_Event__e/fields/OriginComponent__c.field-meta.xml
<CustomField>
    <fullName>OriginComponent__c</fullName>
    <label>OriginComponent</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ErrorLogApp/main/default/objects/CDER_Log_Exception_Event__e/fields/RecordId__c.field-meta.xml
<CustomField>
    <fullName>RecordId__c</fullName>
    <description>The ID of the record associated with a particular log entry.</description>
    <label>RecordId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

ErrorLogApp/main/default/classes/CDER_ErrorLoggerAction.cls
public with sharing class CDER_ErrorLoggerAction {

    @InvocableMethod(label='CDER Log Error' description='CDER Error Logger')
    public static void log(List<CDER_Log_Exception_Event__e> logEventList){
        CDER_ErrorLog__c errorLog = new CDER_ErrorLog__c();
        for(CDER_Log_Exception_Event__e evt :logEventList) {
            System.debug('###Log Platform Event captured: '+evt);
            errorLog.ErrorCause__c =  evt.ErrorCause__c;
            errorLog.ExceptionMessage__c = evt.ExceptionMessage__c;
            errorLog.ExceptionStackTrace__c = evt.ExceptionStackTrace__c;
            errorLog.ExceptionType__c = evt.ExceptionType__c;
            errorLog.LineNumber__c = evt.LineNumber__c;
            errorLog.OriginApplication__c = evt.OriginApplication__c;
            errorLog.OriginComponent__c = evt.OriginComponent__c;
            errorLog.RecordId__c = evt.RecordId__c;
            errorLog.Origin__c = evt.Origin__c;
            errorLog.Status__c = 'New';  //Default
        }
        try {
            insert errorLog;
        }
        catch(Exception e) {
            System.debug('The following exception has occurred: ' + e.getMessage());
        }
        
    }

}