ErrorLogApp/main/default/objects/CDER_ErrorLog__c/CDER_ErrorLog__c.object-meta.xml
<CustomObject>
    <label>CDER_ErrorLog</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>CDER_ErrorLog Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CDER_ErrorLogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ErrorLogApp/main/default/objects/CDER_ErrorLog__c/fields/ErrorCause__c.field-meta.xml
<CustomField>
    <fullName>ErrorCause__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>ErrorCause</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ErrorLogApp/main/default/objects/CDER_ErrorLog__c/fields/ExceptionMessage__c.field-meta.xml
<CustomField>
    <fullName>ExceptionMessage__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>ExceptionMessage</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

ErrorLogApp/main/default/objects/CDER_ErrorLog__c/fields/ExceptionStackTrace__c.field-meta.xml
<CustomField>
    <fullName>ExceptionStackTrace__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>ExceptionStackTrace</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

ErrorLogApp/main/default/objects/CDER_ErrorLog__c/fields/ExceptionType__c.field-meta.xml
<CustomField>
    <fullName>ExceptionType__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>ExceptionType</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ErrorLogApp/main/default/objects/CDER_ErrorLog__c/fields/LineNumber__c.field-meta.xml
<CustomField>
    <fullName>LineNumber__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>LineNumber</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

ErrorLogApp/main/default/objects/CDER_ErrorLog__c/fields/Origin__c.field-meta.xml
<CustomField>
    <fullName>Origin__c</fullName>
    <label>Origin</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Salesforce</fullName>
            </value>
            <value>
                <fullName>Mulesoft</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ErrorLogApp/main/default/objects/CDER_ErrorLog__c/fields/OriginApplication__c.field-meta.xml
<CustomField>
    <fullName>OriginApplication__c</fullName>
    <label>OriginApplication</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>OMUFA</fullName>
            </value>
            <value>
                <fullName>Cares</fullName>
            </value>
            <value>
                <fullName>ResearchIND</fullName>
            </value>
            <value>
                <fullName>PLAIR</fullName>
            </value>
            <value>
                <fullName>OrphanDrug</fullName>
            </value>
            <value>
                <fullName>MeetingRequest</fullName>
            </value>
            <value>
                <fullName>RDRC</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ErrorLogApp/main/default/objects/CDER_ErrorLog__c/fields/OriginComponent__c.field-meta.xml
<CustomField>
    <fullName>OriginComponent__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>OriginComponent</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ErrorLogApp/main/default/objects/CDER_Log_Exception_Event__e/CDER_Log_Exception_Event__e.object-meta.xml
<CustomObject>
    <description>This platform event contains all information need for further Error Handling</description>
    <label>CDER Log Exception Event</label>
    <pluralLabel>CDER Log Exception Events</pluralLabel>
</CustomObject>

ErrorLogApp/main/default/objects/CDER_Log_Exception_Event__e/fields/ErrorCause__c.field-meta.xml
<CustomField>
    <fullName>ErrorCause__c</fullName>
    <label>ErrorCause</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ErrorLogApp/main/default/objects/CDER_Log_Exception_Event__e/fields/ExceptionMessage__c.field-meta.xml
<CustomField>
    <fullName>ExceptionMessage__c</fullName>
    <label>ExceptionMessage</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

ErrorLogApp/main/default/objects/CDER_Log_Exception_Event__e/fields/ExceptionStackTrace__c.field-meta.xml
<CustomField>
    <fullName>ExceptionStackTrace__c</fullName>
    <label>ExceptionStackTrace</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

ErrorLogApp/main/default/objects/CDER_Log_Exception_Event__e/fields/ExceptionType__c.field-meta.xml
<CustomField>
    <fullName>ExceptionType__c</fullName>
    <label>ExceptionType</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ErrorLogApp/main/default/objects/CDER_Log_Exception_Event__e/fields/LineNumber__c.field-meta.xml
<CustomField>
    <fullName>LineNumber__c</fullName>
    <label>LineNumber</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

ErrorLogApp/main/default/objects/CDER_Log_Exception_Event__e/fields/Origin__c.field-meta.xml
<CustomField>
    <fullName>Origin__c</fullName>
    <description>Should contain the Origin Layer, e.g Salesforce or Mulesoft</description>
    <label>Origin</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

ErrorLogApp/main/default/objects/CDER_Log_Exception_Event__e/fields/OriginApplication__c.field-meta.xml
<CustomField>
    <fullName>OriginApplication__c</fullName>
    <label>OriginApplication</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ErrorLogApp/main/default/objects/CDER_Log_Exception_Event__e/fields/OriginComponent__c.field-meta.xml
<CustomField>
    <fullName>OriginComponent__c</fullName>
    <label>OriginComponent</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ErrorLogApp/main/default/classes/CDER_HandleExceptionTest.cls
@isTest(isParallel=true)
private class CDER_HandleExceptionTest {

    //This test asserts the log handler method is publishing Platform Event which is actively subscribed by flow
    @TestSetup
    static void makeData(){
        CDER_Log_Exception_Event__e evt = new CDER_Log_Exception_Event__e();
        evt.ExceptionType__c='Log exception.getTypeName()';
        evt.ErrorCause__c='Log exception.getCause(), make sure to set Cause before throwing';
        evt.ExceptionMessage__c='Log exception.getMessage() output';
        evt.ExceptionStackTrace__c = 'Log exception.getStackTraceString()';
        evt.LineNumber__c ='Log exception.getLineNumber()';
        evt.OriginComponent__c ='Salesforce Apex';
        evt.OriginApplication__c ='Some App Name';
        evt.Origin__c='Salesforce';
        List<CDER_Log_Exception_Event__e> listEvt = new List<CDER_Log_Exception_Event__e>();
        listEvt.add(evt);
        EventBus.publish(listEvt);
        Test.getEventBus().deliver(); 

        try {
            Integer i = 1/0;            
        } catch (Exception e) {
            CDER_HandleException.logException(e,'TestCause');
        }        
    }
    @isTest
    static void testSubscription(){
        try {
            Integer i = 1/0;            
        } catch (Exception e) {
            CDER_HandleException.logException(e,'TestCause');
        }
       // CDER_ErrorLog__c errLog = [SELECT id, ExceptionType__c FROM EventBusSubscriber where Topic='CDER_Log_Exception_Event__e' AND Type='ApexTrigger'].get(0);
       
       EventBusSubscriber subscriber = [SELECT id, status FROM EventBusSubscriber where Topic='CDER_Log_Exception_Event__e'].get(0);
        System.debug('***********subscriber:'+subscriber);

        /*Status can have any of the below value, to verify our Flow is actively listening, this value should be 'Running'
            Running—The subscriber is actively listening to events. If you modify the subscriber, the subscription continues to process events.
            Error— The subscriber was disconnected and stopped receiving published events. 
                    A trigger reaches this state when it exceeds the number of maximum retries with the 
                    EventBus.RetryableException. Trigger assertion failures and unhandled exceptions don’t 
                    cause the error state. We recommend limiting the retries to fewer than nine times to avoid reaching 
                    this state. When you fix and save the trigger, or for a managed package trigger, 
                    if you redeploy the package, the trigger resumes automatically from the tip, starting from new events. 
                    Also, you can resume a trigger subscription in the subscription detail page that you access 
                    from the platform event page.
            Suspended—The subscriber is disconnected and can’t receive events because a Salesforce admin suspended 
                    it or due to an internal error. You can resume a trigger subscription in the subscription detail 
                    page that you access from the platform event page. To resume a process, deactivate it and 
                    then reactivate it. If you modify the subscriber, the subscription resumes automatically from the 
                    tip, starting from new events.
        */
        System.assertEquals(subscriber.status, 'Running', 'CDER_Error_Logger.flow is not actively listening for Errors'); 

    }


    @isTest
    static void testPlatformEvent() {
        Test.startTest();

        List<CDER_ErrorLog__c> evt = [Select id from CDER_ErrorLog__c];
        System.debug('****EVT:'+evt);
        Test.stopTest();
    }
    
}