ErrorLogApp/main/default/objects/CDER_Log_Exception_Event__e/CDER_Log_Exception_Event__e.object-meta.xml
<CustomObject>
    <description>This platform event contains all information need for further Error Handling</description>
    <label>CDER Log Exception Event</label>
    <pluralLabel>CDER Log Exception Events</pluralLabel>
</CustomObject>

ErrorLogApp/main/default/objects/CDER_Log_Exception_Event__e/fields/ErrorCause__c.field-meta.xml
<CustomField>
    <fullName>ErrorCause__c</fullName>
    <label>ErrorCause</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ErrorLogApp/main/default/objects/CDER_Log_Exception_Event__e/fields/ExceptionMessage__c.field-meta.xml
<CustomField>
    <fullName>ExceptionMessage__c</fullName>
    <label>ExceptionMessage</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

ErrorLogApp/main/default/objects/CDER_Log_Exception_Event__e/fields/ExceptionStackTrace__c.field-meta.xml
<CustomField>
    <fullName>ExceptionStackTrace__c</fullName>
    <label>ExceptionStackTrace</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

ErrorLogApp/main/default/objects/CDER_Log_Exception_Event__e/fields/ExceptionType__c.field-meta.xml
<CustomField>
    <fullName>ExceptionType__c</fullName>
    <label>ExceptionType</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ErrorLogApp/main/default/objects/CDER_Log_Exception_Event__e/fields/LineNumber__c.field-meta.xml
<CustomField>
    <fullName>LineNumber__c</fullName>
    <label>LineNumber</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

ErrorLogApp/main/default/objects/CDER_Log_Exception_Event__e/fields/Origin__c.field-meta.xml
<CustomField>
    <fullName>Origin__c</fullName>
    <description>Should contain the Origin Layer, e.g Salesforce or Mulesoft</description>
    <label>Origin</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

ErrorLogApp/main/default/objects/CDER_Log_Exception_Event__e/fields/OriginApplication__c.field-meta.xml
<CustomField>
    <fullName>OriginApplication__c</fullName>
    <label>OriginApplication</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ErrorLogApp/main/default/objects/CDER_Log_Exception_Event__e/fields/OriginComponent__c.field-meta.xml
<CustomField>
    <fullName>OriginComponent__c</fullName>
    <label>OriginComponent</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ErrorLogApp/main/default/objects/CDER_Log_Exception_Event__e/fields/RecordId__c.field-meta.xml
<CustomField>
    <fullName>RecordId__c</fullName>
    <description>The ID of the record associated with a particular log entry.</description>
    <label>RecordId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

ErrorLogApp/main/default/classes/CDER_HandleException.cls
public class CDER_HandleException extends Exception{

    public static String DEFAULT_ORIGIN='Salesforce';
    
    public static void logException(Exception e){
        logException(e,'','','','','');
    }

    public static void logException(Exception e, String cause){
        logException(e, cause, '','','','');
    }

    public static void logException(Exception e, String cause, String relatedToId){
        logException(e, cause, relatedToId,'','','');
    }

    public static void logException(Exception e, String cause, String relatedToId, String app ) {
        logException(e, cause, relatedToId,app,'','');
    }

    public static void logException(Exception e, String cause, String relatedToId, String app, String comp ) {
        logException(e, cause, relatedToId,app,comp,'');
    }

    /*
     * The params to be passed are 
     * e - Exception object
     * cause - Provide specific details on what business funtion is done
     * relatedToId - Pass the Salesforce 18 digit record ID related to this which can provide more details, e.g. Case ID
     * app - Application, e.g., Cares
     * comp - Component, e.g Flow, LWC / APEX Controller
     * origin - Origin layer, e.g Salesforce or Mulesoft
     */
    public static void logException(Exception e, String cause, String relatedToId,  String app, String comp, String origin){
        try
        {
            //Create Platform Event and publish it
            CDER_Log_Exception_Event__e evt = new CDER_Log_Exception_Event__e();
            evt.ErrorCause__c = cause;
            evt.RecordId__c = relatedToId;
            evt.ExceptionMessage__c = e.getMessage();
            evt.ExceptionType__c = e.getTypeName();
            evt.ExceptionStackTrace__c = e.getStackTraceString();
            evt.LineNumber__c = String.valueOf(e.getLineNumber());  
            evt.origin__c = (String.isBlank(origin) == true)? DEFAULT_ORIGIN : origin;       
            evt.OriginComponent__c = comp;
            evt.OriginApplication__c = app;
            EventBus.publish(evt);
        }
        finally {

        }
    }
}